# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Court' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Court
    pod 'AFNetworking', '~> 3.0'
    pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
    pod 'IQKeyboardManager', '~> 4.0'
    pod 'LDProgressView', '~> 1.2'
    pod 'SVProgressHUD'
    pod "DXCustomCallout-ObjC"
    pod 'JTAlertView'
end
